#!/bin/sh

set -e

dpkg-maintscript-helper symlink_to_dir /usr/share/doc/vdr-dbg /usr/share/doc/vdr 2.0.1-1~ -- "$@"

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d vdr-dbg remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

