#!/bin/sh

set -e

dpkg-maintscript-helper symlink_to_dir /usr/share/doc/vdr-dbg /usr/share/doc/vdr 2.0.1-1~ -- "$@"

# Automatically added by dh_installinit
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/vdr-dbg" ]; then
		update-rc.d vdr-dbg defaults >/dev/null || exit $?
	fi
fi
# End automatically added section

